In [12]:
#import numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

#creating numpy array
np_baseball = np.array(baseball)

print(np_baseball)

[180 215 210 210 188 176 209 200]


In [23]:
import numpy as np

# height in inches of major league basketball players
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73]
# Create a numpy array from height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Converting the inches to meters
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 72 73 69 69 71 76 71 73 73 74 74 69 70 73]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542]


In [25]:
#Subsetting numpy arrays
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189]
np_weight_lb = np.array(weight_lb)

#Printing out element at index 13
print(np_weight_lb[13])

#Print out a sub-array that contains the elements at index 10 up to and including index 15.
print(np_weight_lb[10:16])

160
[188 180 185 160 180 185]


In [16]:
# numpy side effects
# having different data types in an array and doing arithmentic operations
#boolean true is 1 and false is 0

np.array([True, 1, 2]) + np.array([3, 4, False])


array([4, 5, 2])

In [11]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

import numpy as np

np_height = np.array(height)
print("The heights are: " +str(np_height))

np_weight = np.array(weight)
print("The weights are: " +str(np_weight))

bmi = np_weight/np_height ** 2
print("The respective bmi are: " +str(bmi))

The heights are: [1.73 1.68 1.71 1.89 1.79]
The weights are: [65.4 59.2 63.6 88.4 68.7]
The respective bmi are: [21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [26]:
# 2D Nnumpy arrays
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)

# Print out the shape of np_baseball
np_baseball.shape

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


(4, 2)

In [27]:
# Subsetting 2D NumPy Arrays
import numpy as np

baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], 
            [76, 231], [71, 180], [73, 188], [73, 180], [74, 185], [74, 160], [69, 180], [70, 185], 
            [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195]] 
np_baseball = np.array(baseball)

# Print out the 10th row of np_baseball
print(np_baseball[9,:])

# Make a new variable, np_weight_lb, containing the entire second column of np_baseball
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)

# Print out height of 12th player
print(np_baseball[11,0])

[ 71 180]
[180 215 210 210 188 176 209 200 231 180 188 180 185 160 180 185 189 185
 219 230 205 230 195]
73


In [34]:
# 2D Arithmetic
baseball = [[74.0, 180.0, 22.99], [74.0, 215.0, 34.69], [72.0, 210.0, 30.78], [72.0, 210.0, 35.43], 
            [73.0, 188.0, 35.71], [69.0, 176.0, 29.39], [69.0, 209.0, 30.77], [71.0, 200.0, 35.07], 
            [76.0, 231.0, 30.19], [71.0, 180.0, 27.05], [73.0, 188.0, 23.88], [73.0, 180.0, 26.96], 
            [74.0, 185.0, 23.29], [74.0, 160.0, 26.11], [69.0, 180.0, 27.55], [70.0, 185.0, 34.27]]

# The new changes after a year (print(updated[:16]))
updated = [[  1.2303559,  -11.16224898, 1.        ],[  1.02614252,  16.09732309,   1.        ],[  1.1544228 ,   5.08167641 ,  1.        ],
           [  0.64427532,  -5.09538071, 1.        ],[  1.00590086,   2.24342718,   1.        ],[  0.97953547,  12.19841763,  1.        ],
           [  0.62874324,  13.72324216, 1.        ],[  1.27075194,  -8.87946313,   1.        ],[  0.47655945, -10.82495536,  1.        ],
           [  0.91699376, -7.01116249, 1.        ],[  1.17179326,   1.19946614,   1.        ],[  1.14509104, -12.00385685,   1.        ],
           [  1.20684945, -13.29830645 ,1.        ],[  1.03436155,   3.01324251,   1.        ],[  0.87747454,  10.51779503,   1.        ],
            [  0.9813308,   -1.55666485, 1.        ]]

#Converting baseball and updated to an array
np_baseball = np.array(baseball)
np_updated = np.array(updated)

#Adding np_baseball and updated and print out the result.
print(np_baseball + np_updated)

# convert the units of height and weight to metric (meters and kilograms, respectively).

# First write the unit of conversion as an array
conversion = np.array([0.0254, 0.453592, 1])

# Multiply np_baseball with conversion and print out the result.
print(np_baseball * conversion)

[[ 75.2303559  168.83775102  23.99      ]
 [ 75.02614252 231.09732309  35.69      ]
 [ 73.1544228  215.08167641  31.78      ]
 [ 72.64427532 204.90461929  36.43      ]
 [ 74.00590086 190.24342718  36.71      ]
 [ 69.97953547 188.19841763  30.39      ]
 [ 69.62874324 222.72324216  31.77      ]
 [ 72.27075194 191.12053687  36.07      ]
 [ 76.47655945 220.17504464  31.19      ]
 [ 71.91699376 172.98883751  28.05      ]
 [ 74.17179326 189.19946614  24.88      ]
 [ 74.14509104 167.99614315  27.96      ]
 [ 75.20684945 171.70169355  24.29      ]
 [ 75.03436155 163.01324251  27.11      ]
 [ 69.87747454 190.51779503  28.55      ]
 [ 70.9813308  183.44333515  35.27      ]]
[[  1.8796    81.64656   22.99    ]
 [  1.8796    97.52228   34.69    ]
 [  1.8288    95.25432   30.78    ]
 [  1.8288    95.25432   35.43    ]
 [  1.8542    85.275296  35.71    ]
 [  1.7526    79.832192  29.39    ]
 [  1.7526    94.800728  30.77    ]
 [  1.8034    90.7184    35.07    ]
 [  1.9304   104.779752  30.19    ]
 [ 